# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a24fc4518c0e601f01781dd29fdbf032ec2d7c107cabac3fea3ee3011db534e8a6505a3a0e65f84137ca7bcdf016e524e595056700e64aa3f82ec9b7d749588f

test:
  secret_key_base: 39fae592b2199f4396ef883192a1010eb8b265bd768ed01345c901f8be66a3a1a241f23327af4311c23a80c886f4db7179f1dba4d734e9d279b67ea0ea36f43d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
